name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - build.zig.zon
      - build.zig
      - src/**
      - protocol/**
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Libraries
        run: sudo apt install -y libwayland-dev libgl-dev libegl-dev wayland-protocols pkg-config
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
      - name: Build
        run: zig build --release=fast
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: zig-out/bin/*
      - name: Nuke Caches
        run: |
          rm -rf ~/.cache/zig
          rm -rf ./zig-out
