name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - build.zig.zon
      - build.zig
      - src/**
      - protocol/**
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y libwayland-dev wayland-protocols pkg-config
      - uses: mlugg/setup-zig@v2
      - run: zig build --release=fast
      - uses: actions/upload-artifact@v4
        with:
          path: zig-out/bin/*
